# Generated by Django 3.2.7 on 2021-09-05 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePool',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image_folder', models.CharField(max_length=1000, unique=True)),
                ('feature_file', models.CharField(default=None, max_length=1000, null=True)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
